name: Build Image

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Decrypt nuget config
      run: Invoke-Expression "docker run --rm -v $(pwd)\web:c:\crypt tobiasfenster/rijndaelfileenc:0.1-1809 --action decrypt --password $env:crypt_pwd --file c:\crypt\nuget.config.enc"
      env:
        crypt_pwd: ${{ secrets.crypt_pwd }}

    - name: Build Docker image
      run: Invoke-Expression ("docker build tobiasfenster/azdevops-wi-reader:" + $env:GITHUB_RUN_ID + "-1809 -f Dockerfile.1809 web")
