name: Build Image

on:
  push:
    tags:
    - 'v*' 

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Decrypt nuget config
      run: Invoke-Expression "docker run --rm -v $(pwd)\web:c:\crypt tobiasfenster/rijndaelfileenc:0.1-1809 --action decrypt --password $env:crypt_pwd --file c:\crypt\nuget.config.enc"
      env:
        crypt_pwd: ${{ secrets.crypt_pwd }}
    
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.docker_user }}
        password: ${{ secrets.docker_pwd }}

    - name: Build and push Docker image
      run: web\build.ps1
